"""Auto-wrapped Modal harness for e31_dedup_cloud.py.

Generated by gpu2modal autowrap on 2026-08-28T16:35:34.
Re-runs the user's plain Python script inside a Modal container.

Usage:
    modal run modal_e31_dedup_cloud.py
"""
from __future__ import annotations
import subprocess, sys, time
from pathlib import Path
import modal

HERE = Path(__file__).parent.resolve()
RESULTS = HERE / "results"
RESULTS.mkdir(exist_ok=True)

image = (
    modal.Image.from_registry("pytorch/pytorch:2.4.0-cuda12.4-cudnn9-devel", add_python="3.11")
    .pip_install("pillow", "pillow-jxl-plugin", "pillow-avif-plugin", "numpy")
    .add_local_file("E:/Projects/ImageBudnling/scripts/e31_dedup_cloud.py", "/app/script.py")
    .add_local_file("E:/Projects/ImageBudnling/scripts/assets_bundle.zip", "/app/assets_bundle.zip")
    .add_local_file("E:/Projects/ImageBudnling/scripts/static_study.py", "/app/static_study.py")
    .add_local_file("E:/Projects/ImageBudnling/scripts/e31_ordering.py", "/app/e31_ordering.py")
)

app = modal.App("autowrap-e31-dedup-cloud", image=image)
results_vol = modal.Volume.from_name("autowrap-e31-dedup-cloud-results", create_if_missing=True)


@app.function(
    timeout=7200,
    memory=8192,
    cpu=2.0,
    volumes={"/results": results_vol},
)
def run_script() -> dict:
    import os, sys
    os.chdir("/app")
    t0 = time.time()
    print(f"[autowrap] starting e31_dedup_cloud.py", flush=True)
    print("[autowrap] CPU-only container", flush=True)
    cmd = ["python", "-u", "/app/script.py"] + []
    print(f"[autowrap] $ {' '.join(cmd)}", flush=True)
    rc = subprocess.call(cmd, cwd="/app")
    elapsed = time.time() - t0
    print(f"[autowrap] script exit rc={rc} elapsed={elapsed:.1f}s", flush=True)

    # Persist any files the script wrote under /app/results/ to the volume
    src = Path("/app/results")
    if src.exists():
        import shutil
        for p in src.rglob("*"):
            if p.is_file():
                rel = p.relative_to(src)
                dst = Path("/results") / rel
                dst.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(p, dst)
        results_vol.commit()
        print(f"[autowrap] persisted results to volume", flush=True)

    print("[autowrap] === DONE ===", flush=True)
    return {"rc": rc, "elapsed_s": round(elapsed, 1)}


@app.local_entrypoint()
def main():
    result = run_script.remote()
    print(f"[local] remote returned: {result}", flush=True)
    # Download volume contents
    import subprocess as sp
    rc = sp.call(["modal", "volume", "get", "--force", "autowrap-e31-dedup-cloud-results", "/", str(RESULTS)])
    print(f"[local] modal volume get rc={rc}; results -> {RESULTS}", flush=True)
